~?!i&32768
~o|295
batchin=?
reports=4-9_import_am_inc2_auto_skim_matrices.rpt
~/
~/
~/begin: 4-9_import_am_inc2_auto_skim_matrices.mac
~/ ...call module 1.31: import data from external database
1.31
~/ ...open am auto skim emmebank
~+|1
..\..\..\skims\auto\am\emmebank
~/ ...import am inc2 auto skim matrices
~+|2|3|3|mf"aa1ds2"|mf"aa1ds2"|n|y
~+|2|3|3|mf"aa1tm2"|mf"aa1tm2"|n|y
q
~#
~/end: 4-9_import_am_inc2_auto_skim_matrices.mac
~/exit emme
~/
q