~?!i&32768
~o|295
batchin=?
reports=8_calculate_friction_factors.rpt
~/
~/
~/begin: 8_calculate_friction_factors.mac
~/ ...call module 3.21: matrix calculations
~/ ...calculate hb work income 3 friction factors
3.21
~+|1|y|mf"hbwfr3"|n|exp(ms"hbwex3"*(mf"aa1cs3"+(mf"aa1ds3"*ms"autoop"*ms"avot3v")))|||y|1,%3%||1,%3%||2
q
~#
~/ ...set externals to 0 to prevent e-e trips
3.21
~+|1|y|mf"hbwfr3"|n|0|||y|%2%,%3%||%2%,%3%||2
q
~#
~/end: 8_calculate_friction_factors.mac
~/exit emme
~/
q
