~?!i&32768
~o|295
batchin=?
reports=9_import_distribution_matrices.rpt
~/
~/
~/begin: 9_import_distribution_matrices.mac
~# ...call module 1.31: import data from external database
~/ ...open daily distribution emmebanks
1.31
~+|1
~/ ...hb work income 2
..\..\..\distribution\hbwork_inc2\emmebank
~+|2|3|3|mf"hbwds2"|mf"hbwds2"|n|y
q
~#
~/end: 9_import_distribution_matrices.mac
~/exit emme
~/
q