~?!i&32768
~o|295
batchin=?
reports=3_initialize_ev_vdfs.rpt
~/
~/
~/begin: 3_initialize_ev_vdfs.mac
~/ ...set active scenario to 1005
s=1005
~/ ...call module 4.12: input/modify functions interactively
~/ ...initialize function table
4.12
~+|1|y
q
~/ ...call module 4.11: input functions using batch entry
~/ ...input evening vdfs
4.11
..\..\..\input\%1%\model\vdfs\ev_vdfs.in
2
~#
~/end: 3_initialize_ev_vdfs.mac
~/exit emme
~/
q
