~?!i&32768
~o|295
batchin=?
reports=3_initialize_ni_vdfs.rpt
~/
~/
~/begin: 3_initialize_ni_vdfs.mac
~/ ...set active scenario to 1006
s=1006
~/ ...call module 4.12: input/modify functions interactively
~/ ...initialize function table
4.12
~+|1|y
q
~/ ...call module 4.11: input functions using batch entry
~/ ...input night vdfs
4.11
..\..\..\input\model\vdfs\ni_vdfs.in
2
~#
~/end: 3_initialize_ni_vdfs.mac
~/exit emme
~/
q
