~?!i&32768
~o|295
batchin=?
reports=10_calculate_drive_alone_utility.rpt
~/
~/
~/begin: 10_calculate_drive_alone_utility.mac
~/ ...call module 3.21: matrix calculations
~/ ...calculate hb college mode choice exponentiated utilities
3.21
~/ ...drive alone
~+|1|y|mf"coeuda"|n
exp
(
ms"autivt"*
(mf"au1btm"-mf"termtm")
~#+
~#ms"autovt"*
~#mf"termtm"
+
ms"autcos"*
mf"au1bct"
)
~+|||y|1,%1%||1,%1%||2
q
~#
~/end: 10_calculate_drive_alone_utility.mac
~/exit emme
~/
q
