REM am
call batchfiles\setup\freeflow\am_setup_ff.bat
REM md
call batchfiles\setup\freeflow\md_setup_ff.bat
REM pm
call batchfiles\setup\freeflow\pm_setup_ff.bat
REM ev
call batchfiles\setup\freeflow\ev_setup_ff.bat
REM ni
call batchfiles\setup\freeflow\ni_setup_ff.bat