~?!i&32768
~o|295
batchin=?
reports=3-9-9_input_md_transittriptable.rpt
~/
~/
~/begin: 3-9-9_input_md_transittriptable.mac
~# ...call module 1.31: import data from external database
~/ ...open md auto transit trip table emmebank
1.31
~+|1
~/ ...import trip tables
..\..\..\..\TripTables\Transit\WalkAccess\emmebank
~+|2|3|3|mf"mtrnwa"|mf"mtrnwa"|n|y
q
~#
~/end: 3-9-9_input_md_transittriptable.mac
~/exit emme
~/
q
