~?!i&32768
~o|295
batchin=?
reports=medium_trucks.rpt
~/
~/ ...call module 3.21: matrix calculations
~/ ...balance refactored medium truck attractions to productions
3.21
~+|1|y|ms"mtprof"|n|mo"mtprof"|||n||2
~+|1|y|ms"mtattf"|n|md"mtattf"|||n||2
~+|1|y|ms"mtatfe"|n|md"mtattf"|||y|%2%,%3%|||2
~+|1|y|md"mtattf"|n|md"mtattf"*((ms"mtprof"-ms"mtatfe")/(ms"mtattf"-ms"mtatfe"))|||y|1,%1%||2
q
~#
~/end: 2_balanced_refactored_atrractions.mac.mac
~/exit emme
~/
q
