~?!i&32768
~o|295
batchin=?
reports=oto.rpt
~/
~/ ...call module 3.22: matrix balancing
~/ ...two dimensional balancing
~/ ...matrix to be balanced: mf"temp03"
~/ ...totals on origins: mo"otopro"
~/ ...totals on destinations: md"otoatt"
~/ ...saved balanced matrix: mf"otodst"
~/ ...calculate nhb other/other distribution
3.22
~+|1|mf"temp03"|mo"otopro"|md"otoatt"|y
~+|1,%3%||1,%3%|||2|1|mf"otodst"|n|2
q
~#
~/end: 9_calculate_distribution.mac
~/exit emme
~/
q
