~?!i&32768
~o|295
batchin=?
reports=terminal_time.rpt
~/ ----------------------------------------------------
~/ --- Initialize matrix directory
~/ ----------------------------------------------------
~+|3.12|7|y|q
~/ ----------------------------------------------------
~/ --- Initialize Origin Matrices
~/ ----------------------------------------------------
3.12
~+|1|mo01|prodtt|terminal time at production end|0
~+|1|mo02|tazacr|taz area (in acres)|0
~/ ----------------------------------------------------
~/ --- Initialize Destination Matrices
~/ ----------------------------------------------------
~+|1|md01|attrtt|terminal time at attraction end|0
~/ ----------------------------------------------------
~/ --- Initialize Full Matrices
~/ ----------------------------------------------------
~+|1|mf01|termtm|total terminal time|0
~+|1|mf02|izdist|intrazonal distance|0
~+|1|mf03|izatim|intrazonal time (auto) @ 15 mph|0
~+|1|mf04|izbtim|intrazonal time (bike) @ 10 mph|0
~+|1|mf05|izwtim|intrazonal time (walk) @ 3 mph|0
q
~/ ----------------------------------------------------
~/ --- Input Matrix Data
~/ ----------------------------------------------------
~+|3.11|..\..\parameters\terminaltimes\origin_tt.in|2|
~+|3.11|..\..\parameters\terminaltimes\destination_tt.in|2|
~+|3.11|..\..\parameters\taz\taz_acres.in|2|
~/ ----------------------------------------------------
~/ --- Calculate Terminal Time
~/ ----------------------------------------------------
~+|3.21|1|y|mf"termtm"|n|mo"prodtt"+md"attrtt"|||n|2|q
~/ ----------------------------------------------------
~/ --- Calculate Intrazonal Skims
~/ ----------------------------------------------------
3.21
~+|1|y|mf"izdist"|n|sqrt(mo"tazacr"/640)*45/60*(p.eq.q)|||n|2
~+|1|y|mf"izatim"|n|mf"izdist"*(60/15)|||n|2
~+|1|y|mf"izbtim"|n|mf"izdist"*(60/10)|||n|2
~+|1|y|mf"izwtim"|n|mf"izdist"*(60/3)|||n|2
q
~/
~/exit emme
~/
q
