~?!i&32768
~o|295
batchin=?
reports=4_initialize_iz_tt_destination_matrices.rpt
~/
~/
~/begin: 4_initialize_iz_tt_destination_matrices.mac
~/ ...set active scenario to 9999
s=9999
~/ ...call module 3.12: input/modify matrices interactively
~/ ...initialize full matrices
3.12
~+|1|md01|attrtt|terminal time at attraction end|0
q
~#
~/end: 4_initialize_iz_tt_destination_matrices.mac
~/exit emme
~/
q
