~?!i&32768
~o|295
batchin=?
reports=hb4.rpt
~/
~/ ...call module 3.21: matrix calculations
~/ ...calculate hb work income 4 choice exponentiated utilities
3.21
~/ ...shared ride 2
~+|1|y|mf"eus2"|n
exp
(
ms"asccs2"
+
ms"autivt"*
mf"s2btm"
~#(mf"s2btm"-mf"termtm")
~#+
~#ms"autovt"*
~#mf"termtm"
+
ms"autcos"*
mf"s2bct"
)
~+|||y|1,%3%||1,%3%||2
q
~#
~/end: 5_calculate_shared_ride_2_utility.mac
~/exit emme
~/
q
