~?!i&32768
~o|295
batchin=?
reports=heavy_trucks.rpt
~/
~/ ...call module 3.21: matrix calculations
~/ ...balance refactored heavy truck attractions to productions
3.21
~+|1|y|ms"htprof"|n|mo"htprof"|||n||2
~+|1|y|ms"htattf"|n|md"htattf"|||n||2
~+|1|y|ms"htatfe"|n|md"htattf"|||y|%2%,%3%|||2
~+|1|y|md"htattf"|n|md"htattf"*((ms"htprof"-ms"htatfe")/(ms"htattf"-ms"htatfe"))|||y|1,%1%||2
q
~#
~/end: 2_balanced_refactored_atrractions.mac.mac
~/exit emme
~/
q
