~?!i&32768
~o|295
batchin=?
reports=heavy_trucks.rpt
~/
~/ ...call module 3.22: matrix balancing
~# ...change module parameters:
~# ...maximum number of iterations for balancing = 100
~# ...maximum relative error on totals for balancing = .0001
3.22
~+|3|100|0.0001|y
~/ ...distribute heavy truck trips
~+|1|mf"temp03"|mo"htprof"|md"htattf"|y|1,%3%||1,%3%||~?q=3|2||2|1|mf"hvydis"|n|2
q
~#
~/end: 4_distribute_truck_trips.mac
~/exit emme
~/
q
