~?!i&32768
~o|295
batchin=?
reports=assign.rpt
~/
s=1002
2.41
~# ...sum total sov work vehicles
~+|1|y|@sovw|n|@hbw1+@hbw2+@hbw3+@hbw4||*|2|2
~# ...calculate medium and heavy truck vehicles
~+|1|y|@mveh|n|@mediu/1.5||*|2|2
~+|1|y|@hveh|n|@heavy/2||*|2|2
~# ...calculate bus vehicles
~+|1|y|@bveh|n|@trnv3/2||*|2|2
~# ...sum total vehicles on links
~+|1|y|@tveh|n|@sov+@sovw+@hov2+@hov3+@vpool+@light+@mveh+@hveh+@bveh||*|2|2
q
~#
~/end: 13_calculate_total_vehicles.mac
~/exit emme
~/
q