~?!i&32768
~o|295
batchin=?
reports=3-9-9_input_am_transittriptable.rpt
~/
~/
~/begin: 3-9-9_input_am_transittriptable.mac
~# ...call module 1.31: import data from external database
~/ ...open am auto transit trip table emmebank
1.31
~+|1
~/ ...import trip tables
..\..\..\..\TripTables\all\emmebank
~+|2|3|3|mf"atrnwa"|mf"atrnwa"|n|y
q
~#
~/end: 3-9-9_input_am_transittriptable.mac
~/exit emme
~/
q
