~?!i&32768
~o|295
batchin=?
reports=hbschool.rpt
~/
~/ ...call module 3.22: matrix balancing
~/ ...two dimensional balancing
~/ ...matrix to be balanced: mf"temp03"
~/ ...totals on origins: mo"schpro"
~/ ...totals on destinations: md"schatt"
~/ ...saved balanced matrix: mf"schdst"
~/ ...calculate hb school distribution
3.22
~+|1|mf"temp03"|mo"schpro"|md"schatt"|y
~+|1,%3%||1,%3%|||2|1|mf"schdst"|n|2
q
~#
~/end: 9_calculate_distribution.mac
~/exit emme
~/
q
