~?!i&32768
~o|295
batchin=?
reports=trip_distribution.rpt
~/ ----------------------------------------------------------------------------------
~/ --- Set Flag for External to External Trips to Zero
~/ ----------------------------------------------------------------------------------
~+|3.21|1|y|mf"intflg"|n|0|||y|ga20||ga20||2|q
~/ ----------------------------------------------------------------------------------
~/ --- Set maxium iterations to 100 and max error to 0.0001 for Trip Distribution
~/ ----------------------------------------------------------------------------------
~+|3.22|3|100|0.0001|y|q
~/ ----------------------------------------------------------------------------------
~/ --- Combine Shopping and Other Productions and Attractions together
~/ ----------------------------------------------------------------------------------
~+|3.21|1|y|mo"hbopro"|n|mo"hbopro"+mo"hsppro"|||n|2|q
~+|3.21|1|y|md"hboatt"|n|md"hboatt"+md"hspatt"|||n|2|q
~/ ----------------------------------------------------------------------------------
~/ --- Combine Commercial Vehicle and Work to Other Productions and Attractions together
~/ ----------------------------------------------------------------------------------
~+|3.21|1|y|mo"wtopro"|n|mo"wtopro"+mo"cvhpro"|||n|2|q
~+|3.21|1|y|md"wtoatt"|n|md"wtoatt"+md"cvhatt"|||n|2|q
~/ ----------------------------------------------------------------------------------
~/ --- Import am bi-directional cost and distance skims for sov nonwork
~/ ----------------------------------------------------------------------------------
~+|1.31|1|..\..\Skims\BiDirectional\all\emmebank|2|3|3|mf"au1bcs"|mf"cost"|n|y|q
~+|1.31|1|..\..\Skims\BiDirectional\all\emmebank|2|3|3|mf"au1bds"|mf"dist"|n|y|q
~+|1.31|1|..\..\Skims\Auto\AM\emmebank|2|3|3|mf"brsov"|mf"brdg"|n|y|q
~/ ----------------------------------------------------------------------------------
~/ --- Calculate College Trip Distribution
~/ ----------------------------------------------------------------------------------
~+|3.21|1|y|mf"fri"|n|0|||n|2|q
~+|3.21|1|y|mf"fri"|n|exp(ms"colexp"*(mf"cost"+(mf"dist"*ms"autoop"*ms"avotda")+0*mf"brdg"))|||y|1,%3%||1,%3%||2|q
~+|3.21|1|y|mf"fri"|n|0|||y|%2%,%3%||%2%,%3%||2|q
~+|3.22|1|mf"fri"|mo"colpro"|md"colatt"|y|1,%3%||1,%3%|||2|1|mf"coldst"|n|2|q
~/ ----------------------------------------------------------------------------------
~/ --- Import am bi-directional cost and distance skims for sov work income #1
~/ ----------------------------------------------------------------------------------
~+|1.31|1|..\..\Skims\BiDirectional\all\emmebank|2|3|3|mf"ah1bcs"|mf"cost"|n|y|q
~+|1.31|1|..\..\Skims\BiDirectional\all\emmebank|2|3|3|mf"ah1bds"|mf"dist"|n|y|q
~/ ----------------------------------------------------------------------------------
~/ --- Calculate Home Based Work Income #1 Trip Distribution
~/ ----------------------------------------------------------------------------------
~+|3.21|1|y|mf"fri"|n|0|||n|2|q
~+|3.21|1|y|mf"fri"|n|exp(ms"hbwex1"*(mf"cost"+(mf"dist"*ms"autoop"*ms"avot1v")+0*mf"brdg"))|||y|1,%3%||1,%3%||2|q
~+|3.21|1|y|mf"fri"|n|0|||y|%2%,%3%||%2%,%3%||2|q
~+|3.22|1|mf"fri"|mo"hbw1pro"|md"hbw1att"|y|1,%3%||1,%3%|||2|1|mf"hbwds1"|n|2|q
~/ ----------------------------------------------------------------------------------
~/ --- Import am bi-directional cost and distance skims for sov work income #2
~/ ----------------------------------------------------------------------------------
~+|1.31|1|..\..\Skims\BiDirectional\all\emmebank|2|3|3|mf"ah2bcs"|mf"cost"|n|y|q
~+|1.31|1|..\..\Skims\BiDirectional\all\emmebank|2|3|3|mf"ah2bds"|mf"dist"|n|y|q
~/ ----------------------------------------------------------------------------------
~/ --- Calculate Home Based Work Income #2 Trip Distribution
~/ ----------------------------------------------------------------------------------
~+|3.21|1|y|mf"fri"|n|0|||n|2|q
~+|3.21|1|y|mf"fri"|n|exp(ms"hbwex2"*(mf"cost"+(mf"dist"*ms"autoop"*ms"avot2v")+0*mf"brdg"))|||y|1,%3%||1,%3%||2|q
~+|3.21|1|y|mf"fri"|n|0|||y|%2%,%3%||%2%,%3%||2|q
~+|3.22|1|mf"fri"|mo"hbw2pro"|md"hbw2att"|y|1,%3%||1,%3%|||2|1|mf"hbwds2"|n|2|q
~/ ----------------------------------------------------------------------------------
~/ --- Import am bi-directional cost and distance skims for sov work income #3
~/ ----------------------------------------------------------------------------------
~+|1.31|1|..\..\Skims\BiDirectional\all\emmebank|2|3|3|mf"ah3bcs"|mf"cost"|n|y|q
~+|1.31|1|..\..\Skims\BiDirectional\all\emmebank|2|3|3|mf"ah3bds"|mf"dist"|n|y|q
~/ ----------------------------------------------------------------------------------
~/ --- Calculate Home Based Work Income #3 Trip Distribution
~/ ----------------------------------------------------------------------------------
~+|3.21|1|y|mf"fri"|n|0|||n|2|q
~+|3.21|1|y|mf"fri"|n|exp(ms"hbwex3"*(mf"cost"+(mf"dist"*ms"autoop"*ms"avot3v")+0*mf"brdg"))|||y|1,%3%||1,%3%||2|q
~+|3.21|1|y|mf"fri"|n|0|||y|%2%,%3%||%2%,%3%||2|q
~+|3.22|1|mf"fri"|mo"hbw3pro"|md"hbw3att"|y|1,%3%||1,%3%|||2|1|mf"hbwds3"|n|2|q
~/ ----------------------------------------------------------------------------------
~/ --- Import am bi-directional cost and distance skims for sov work income #4
~/ ----------------------------------------------------------------------------------
~+|1.31|1|..\..\Skims\BiDirectional\all\emmebank|2|3|3|mf"ah4bcs"|mf"cost"|n|y|q
~+|1.31|1|..\..\Skims\BiDirectional\all\emmebank|2|3|3|mf"ah4bds"|mf"dist"|n|y|q
~/ ----------------------------------------------------------------------------------
~/ --- Calculate Home Based Work Income #4 Trip Distribution
~/ ----------------------------------------------------------------------------------
~+|3.21|1|y|mf"fri"|n|0|||n|2|q
~+|3.21|1|y|mf"fri"|n|exp(ms"hbwex4"*(mf"cost"+(mf"dist"*ms"autoop"*ms"avot4v")+0*mf"brdg"))|||y|1,%3%||1,%3%||2|q
~+|3.21|1|y|mf"fri"|n|0|||y|%2%,%3%||%2%,%3%||2|q
~+|3.22|1|mf"fri"|mo"hbw4pro"|md"hbw4att"|y|1,%3%||1,%3%|||2|1|mf"hbwds4"|n|2|q
~/ ----------------------------------------------------------------------------------
~/ --- Import midday bi-directional cost and distance skims for nonwork purposes
~/ ----------------------------------------------------------------------------------
~+|1.31|1|..\..\Skims\BiDirectional\all\emmebank|2|3|3|mf"mu1bcs"|mf"cost"|n|y|q
~+|1.31|1|..\..\Skims\BiDirectional\all\emmebank|2|3|3|mf"mu1bds"|mf"dist"|n|y|q
~/ ----------------------------------------------------------------------------------
~/ --- Calculate Home Based Other Trip Distribution
~/ ----------------------------------------------------------------------------------
~+|3.21|1|y|mf"fri"|n|0|||n|2|q
~+|3.21|1|y|mf"fri"|n|exp(ms"hboexp"*(mf"cost"+(mf"dist"*ms"autoop"*ms"mvotda")+0*mf"brdg"))|||y|1,%3%||1,%3%||2|q
~+|3.21|1|y|mf"fri"|n|0|||y|%2%,%3%||%2%,%3%||2|q
~+|3.22|1|mf"fri"|mo"hbopro"|md"hboatt"|y|1,%3%||1,%3%|||2|1|mf"hbodst"|n|2|q
~/ ----------------------------------------------------------------------------------
~/ --- Calculate Home Based School Trip Distribution
~/ ----------------------------------------------------------------------------------
~+|3.21|1|y|mf"fri"|n|0|||n|2|q
~+|3.21|1|y|mf"fri"|n|exp(ms"schexp"*(mf"cost"+(mf"dist"*ms"autoop"*ms"mvotda")+0*mf"brdg"))|||y|1,%3%||1,%3%||2|q
~+|3.21|1|y|mf"fri"|n|0|||y|%2%,%3%||%2%,%3%||2|q
~+|3.22|1|mf"fri"|mo"schpro"|md"schatt"|y|1,%3%||1,%3%|||2|1|mf"schdst"|n|2|q
~/ ----------------------------------------------------------------------------------
~/ --- Calculate Non-Home Other to Other Trip Distribution
~/ ----------------------------------------------------------------------------------
~+|3.21|1|y|mf"fri"|n|0|||n|2|q
~+|3.21|1|y|mf"fri"|n|exp(ms"otoexp"*(mf"cost"+(mf"dist"*ms"autoop"*ms"mvotda")+0*mf"brdg"))|||y|1,%3%||1,%3%||2|q
~+|3.21|1|y|mf"fri"|n|0|||y|%2%,%3%||%2%,%3%||2|q
~+|3.22|1|mf"fri"|mo"otopro"|md"otoatt"|y|1,%3%||1,%3%|||2|1|mf"otodst"|n|2|q
~/ ----------------------------------------------------------------------------------
~/ --- Calculate Non-Home Work to Other Trip Distribution
~/ ----------------------------------------------------------------------------------
~+|3.21|1|y|mf"fri"|n|0|||n|2|q
~+|3.21|1|y|mf"fri"|n|exp(ms"wkoexp"*(mf"cost"+(mf"dist"*ms"autoop"*ms"mvotda")+0*mf"brdg"))|||y|1,%3%||1,%3%||2|q
~+|3.21|1|y|mf"fri"|n|0|||y|%2%,%3%||%2%,%3%||2|q
~+|3.22|1|mf"fri"|mo"wtopro"|md"wtoatt"|y|1,%3%||1,%3%|||2|1|mf"wkodst"|n|2|q
~/ ----------------------------------------------------------------------------------
~/ --- Import medium truck cost and distance skims
~/ ----------------------------------------------------------------------------------
~+|1.31|1|..\..\Skims\BiDirectional\all\emmebank|2|3|3|mf"bmedcs"|mf"cost"|n|y|q
~+|1.31|1|..\..\Skims\BiDirectional\all\emmebank|2|3|3|mf"bmedds"|mf"dist"|n|y|q
~/ ----------------------------------------------------------------------------------
~/ --- Calculate Medium Truck Trip Distribution
~/ ----------------------------------------------------------------------------------
~+|3.21|1|y|mf"fri"|n|0|||n|2|q
~+|3.21|1|y|mf"fri"|n|exp(-0.0053*(mf"cost"+(mf"dist"*ms"medop"*.0133)))*mf"intflg"|||y|1,%3%||1,%3%||2|q
~+|3.22|1|mf"fri"|mo"mtkpro"|md"mtkatt"|y|1,%3%||1,%3%||~?q=3|2||2|1|mf"meddis"|n|2|q
~/ ----------------------------------------------------------------------------------
~/ --- Import heavy truck cost and distance skims
~/ ----------------------------------------------------------------------------------
~+|1.31|1|..\..\Skims\BiDirectional\all\emmebank|2|3|3|mf"bhvycs"|mf"cost"|n|y|q
~+|1.31|1|..\..\Skims\BiDirectional\all\emmebank|2|3|3|mf"bhvyds"|mf"dist"|n|y|q
~/ ----------------------------------------------------------------------------------
~/ --- Calculate Heavy Truck Trip Distribution
~/ ----------------------------------------------------------------------------------
~+|3.21|1|y|mf"fri"|n|0|||n|2|q
~+|3.21|1|y|mf"fri"|n|exp(-0.00001*(mf"cost"+(mf"dist"*ms"hvyop"*.0120)))*mf"intflg"|||y|1,%3%||1,%3%||2|q
~+|3.22|1|mf"fri"|mo"htkpro"|md"htkatt"|y|1,%3%||1,%3%||~?q=3|2||2|1|mf"hvydis"|n|2|q
~/ ----------------------------------------------------------------------------------
~/ --- Add in SeaTac Aiport OD Trip Table's to HBO and WKO Distribution
~/ ----------------------------------------------------------------------------------
~+|3.21|1|y|mf"hbodst"|n|mf"hbodst"+(mf"airport"*0.75)|||y|1,%3%||1,%3%||2|q
~+|3.21|1|y|mf"wkodst"|n|mf"wkodst"+(mf"airport"*0.25)|||y|1,%3%||1,%3%||2|q
~/ ----------------------------------------------------------------------------------
~/ --- Add in JBLM workers OD Trip Table's to HBW 1 and HBW2 Trip Tables
~/ ----------------------------------------------------------------------------------
~+|3.21|1|y|mf"hbwds1"|n|mf"hbwds1"+(mf"jblm"*0.75)|||y|1,%3%||1,%3%||2|q
~+|3.21|1|y|mf"hbwds2"|n|mf"hbwds2"+(mf"jblm"*0.25)|||y|1,%3%||1,%3%||2|q
~/ ----------------------------------------------------------------------------------
~/ --- Exit Emme
~/ ----------------------------------------------------------------------------------
~/
q
