~?!i&32768
~o|295
batchin=?
reports=4_initialize_origin_matrices.rpt
~/
~/
~/begin: 4_initialize_origin_matrices.mac
~/ ...call module 3.12: input/modify matrices interactively
~/ ...initialize origin matrices
3.12
~+|1|mo01|ltprof|light truck productions - refactored|0
~+|1|mo02|mtprof|medium truck productions - refactored|0
~+|1|mo03|htprof|heavy truck productions - refactored|0
q
~#
~/end: 4_initialize_origin_matrices.mac
~/exit emme
~/
q
