~?!i&32768
~o|295
batchin=?
reports=hbw3.rpt
~/
~/ ...call module 3.21: matrix calculations
~/ ...calculate hb work income 3 friction factors
3.21
~+|1|y|mf"temp03"|n|exp(ms"hbwex3"*(mf"temp01"+(mf"temp02"*ms"autoop"*ms"avot3v")))|||y|1,%3%||1,%3%||2
q
~#
~/ ...set externals to 0 to prevent e-e trips
3.21
~+|1|y|mf"temp03"|n|0|||y|%2%,%3%||%2%,%3%||2
q
~#
~/end: 2_calculate_friction_factors.mac
~/exit emme
~/
q
