~?!i&32768
~o|295
batchin=?
reports=hbw3.rpt
~/
~/ ...call module 3.22: matrix balancing
~/ ...two dimensional balancing
~/ ...matrix to be balanced: mf"temp03"
~/ ...totals on origins: mo"hbwpr3"
~/ ...totals on destinations: md"hbwat3"
~/ ...saved balanced matrix: mf"hbwds3"
~/ ...calculate hb work income 3 distribution
3.22
~+|1|mf"temp03"|mo"hbwpr3"|md"hbwat3"|y
~+|1,%3%||1,%3%|||2|1|mf"hbwds3"|n|2
q
~#
~/end: 3_calculate_distribution.mac
~/exit emme
~/
q
