~?!i&32768
~o|295
batchin=?
reports=8_export_files_for_urbansim.rpt
~/
~/
~/begin: 8_export_files_for_urbansim.mac
~/ ...call module 3.14: output matrices
~/ ...export vehicle trip tables
batchout=?
3.14
~+|3|mf"aau1tm"||n|n|n|mfaau1tm.rpt|q
3.14
~+|3|mf"aau2tm"||n|n|n|mfaau2tm.rpt|q
3.14
~+|3|mf"aau3tm"||n|n|n|mfaau3tm.rpt|q
3.14
~+|3|mf"aau1cs"||n|n|n|mfaau1cs.rpt|q
3.14
~+|3|mf"aau1ds"||n|n|n|mfaau1ds.rpt|q
~#
~/end: 8_export_files_for_urbansim.mac
~/exit emme
~/
q