call batchfiles\feedback\am_all_mode_feedback_skims.bat
call batchfiles\feedback\md_all_mode_feedback_skims.bat
call batchfiles\feedback\pm_all_mode_feedback_skims.bat
call batchfiles\feedback\ev_all_mode_feedback_skims.bat