~?!i&32768
~o|295
batchin=?
reports=hbw2.rpt
~/
~/ ...call module 3.21: matrix calculations
~/ ...calculate hb work income 2 mode choice exponentiated utilities
3.21
~/ ...drive alone
~+|1|y|mf"euda"|n
exp
(
ms"autivt"*
mf"dabtm"
~#(mf"dabtm"-mf"termtm")
~#+
~#ms"autovt"*
~#mf"termtm"
+
ms"autcos"*
mf"dabct"
)
~+|||y|1,%3%||1,%3%||2
q
~#
~/end: 4_calculate_drive_alone_utility.mac
~/exit emme
~/
q
