~?!i&32768
~o|295
batchin=?
reports=4_initialize_origin_matrices.rpt
~/
~/
~/begin: 4_initialize_origin_matrices.mac
~/ ...call module 3.12: input/modify matrices interactively
~/ ...initialize origin matrices
3.12
~+|1|mo01|hhsiz1|1 person hhs|0
~+|1|mo02|hhsiz2|2 person hhs|0
~+|1|mo03|hhsiz3|3 person hhs|0
~+|1|mo04|hhsiz4|4+ person hhs|0
~+|1|mo05|hhtot|total hhs|0
~+|1|mo06|hhsize|average hh size|0
q
~#
~/end: 4_initialize_origin_matrices.mac
~/exit emme
~/
q
