~?!i&32768
~o|295
batchin=?
reports=6_initialize_full_matrices.rpt
~/
~/
~/begin: 6_initialize_full_matrices.mac
~/ ...call module 3.12: input/modify matrices interactively
~/ ...initialize full matrices
3.12
~+|1|mf01|hhemp|household/employment data|0
~+|1|mf02|vehmtx|vehicle availability cross class|0
~+|1|mf03|vacon|conversion from hhemp to vehmtx format|0
q
~#
~/end: 6_initialize_full_matrices.mac
~/exit emme
~/
q
