~?!i&32768
~o|295
batchin=?
reports=hbshop.rpt
~/
~/ ...call module 3.22: matrix balancing
~/ ...two dimensional balancing
~/ ...matrix to be balanced: mf"temp03"
~/ ...totals on origins: mo"hsppro"
~/ ...totals on destinations: md"hspatt"
~/ ...saved balanced matrix: mf"hspdst"
~/ ...calculate hb shop distribution
3.22
~+|1|mf"temp03"|mo"hsppro"|md"hspatt"|y
~+|1,%3%||1,%3%|||2|1|mf"hspdst"|n|2
q
~#
~/end: 9_calculate_distribution.mac
~/exit emme
~/
q
