~?!i&32768
~o|295
batchin=?
reports=14_transpose_attractions.rpt
~/
~/
~/begin: 14_transpose_attractions.mac
~/ ...call module 3.21: matrix calculations
~/ ...transpose truck attractions (from origin vectors)
3.21
~+|1|y|md"ltatt"|n|mo"ltatt"'|||y|*|2
~+|1|y|md"mtatt"|n|mo"mtatt"'|||y|*|2
~+|1|y|md"htatt"|n|mo"htatt"'|||y|*|2
q
~#
~/end: 14_transpose_attractions.mac
~/exit emme
~/
q
