~?!i&32768
~o|295
batchin=?
reports=15_add_special_generators.rpt
~/
~/
~/begin: 15_add_special_generators.mac
~/ ...call module 3.21: matrix calculations
~/ ...add special generator trips to attractions
3.21
~+|1|y|md"ltatt"|n|md"ltatt"+md"spllgt"|||n|2
~+|1|y|md"mtatt"|n|md"mtatt"+md"splmed"|||n|2
~+|1|y|md"htatt"|n|md"htatt"+md"splhvy"|||n|2
q
~#
~/end: 15_add_special_generators.mac
~/exit emme
~/
q
