~?!i&32768
~o|295
batchin=?
reports=hb_college.rpt
~/
~/ ...call module 3.22: matrix balancing
~/ ...two dimensional balancing
~/ ...matrix to be balanced: mf"temp03"
~/ ...totals on origins: mo"colpro"
~/ ...totals on destinations: md"colatt"
~/ ...saved balanced matrix: mf"coldst"
~/ ...calculate hb college distribution
3.22
~+|1|mf"temp03"|mo"colpro"|md"colatt"|y
~+|1,%3%||1,%3%|||2|1|mf"coldst"|n|2
q
~#
~/end: 9_calculate_distribution.mac
~/exit emme
~/
q
