~?!i&32768
~o|295
batchin=?
reports=hbw1.rpt
~/
~/ ...call module 3.22: matrix balancing
~/ ...two dimensional balancing
~/ ...matrix to be balanced: mf"temp03"
~/ ...totals on origins: mo"hbwpr1"
~/ ...totals on destinations: md"hbwat1"
~/ ...saved balanced matrix: mf"hbwds1"
~/ ...calculate hb work income 1 distribution
3.22
~+|1|mf"temp03"|mo"hbwpr1"|md"hbwat1"|y
~+|1,%3%||1,%3%|||2|1|mf"hbwds1"|n|2
q
~#
~/end: 9_calculate_distribution.mac
~/exit emme
~/
q
