~?!i&32768
~o|295
batchin=?
reports=hv_school.rpt
~/
~/ ...call module 3.21: matrix calculations
~/ ...calculate hb school mode choice exponentiated utilities
3.21
~/ ...shared ride 3+
~+|1|y|mf"eus3"|n
exp
(
ms"asccs3"
+
ms"autivt"*
(mf"s3btm"-mf"termtm")
~#+
~#ms"autovt"*
~#mf"termtm"
~#+
~#ms"autcos"*
~#mf"s3bct"
)
~+|||y|1,%3%||1,%3%||2
q
~#
~/end: 6_calculate_shared_ride_3+_utility.mac
~/exit emme
~/
q
