~?!i&32768
~o|295
batchin=?
reports=3_initialize_pm_vdfs.rpt
~/
~/
~/begin: 3_initialize_pm_vdfs.mac
~/ ...set active scenario to 1003
s=1003
~/ ...call module 4.12: input/modify functions interactively
~/ ...initialize function table
4.12
~+|1|y
q
~/ ...call module 4.11: input functions using batch entry
~/ ...input pm vdfs
4.11
..\..\..\model\vdfs\pm_vdfs.in
2
~#
~/end: 3_initialize_pm_vdfs.mac
~/exit emme
~/
q
