REM am
call batchfiles\setup\congested\am_setup.bat
REM md
call batchfiles\setup\congested\md_setup.bat
REM pm
call batchfiles\setup\congested\pm_setup.bat
REM ev
call batchfiles\setup\congested\ev_setup.bat
REM ni
call batchfiles\setup\congested\ni_setup.bat