~?!i&32768
~o|295
batchin=?
reports=10_import_mode_share_matrices.rpt
~/
~/
~/begin: 10_import_mode_share_matrices.mac
~# ...call module 1.31: import data from external database
~/ ...open daily mode share emmebanks
1.31
~+|1
~/ ...hb work income 3
..\..\..\modechoice\hbwork_inc3\emmebank
~+|2|3|3|mf"w3shtd"|mf"w3shtd"|n|y
q
~#
~/end: 10_import_mode_share_matrices.mac
~/exit emme
~/
q