~?!i&32768
~o|295
batchin=?
reports=9_import_distribution_matrices.rpt
~/
~/
~/begin: 9_import_distribution_matrices.mac
~# ...call module 1.31: import data from external database
~/ ...open daily distribution emmebanks
1.31
~+|1
~/ ...hb work income 3
..\..\..\distribution\all\emmebank
~+|2|3|3|mf"hbwds3"|mf"hbwds3"|n|y
q
~#
~/end: 9_import_distribution_matrices.mac
~/exit emme
~/
q