~?!i&32768
~o|295
batchin=?
batchout=?
reports=batchout_truck_attractions.rpt
~/
~/
~/begin: batchout_truck_attractions.mac
~/ ...call module 3.14: output matrices
3.14
~# ...export matrices
~+|3|md"ltattf"||n|n|light_truck_attractions.in
q
3.14
~# ...export matrices
~+|3|md"mtattf"||n|n|medium_truck_attractions.in
q
3.14
~# ...export matrices
~+|3|md"htattf"||n|n|heavy_truck_attractions.in
q
~#
~/end: batchout_truck_attractions.mac
~/exit emme
~/
q