~?!i&32768
~o|295
batchin=?
reports=hh_trip_generation.rpt
~/ ----------------------------------------------------------------------
~/ --- Balance college productions to college attractions
~/ ----------------------------------------------------------------------
~+|3.21|1|y|ms997|n|mo"colpro"|||n||2|q
~+|3.21|1|y|ms998|n|md"colatt"|||n||2|q
~+|3.21|1|y|ms995|n|mo"colpro"|||y|%2%,%3%|||2|q
~+|3.21|1|y|ms999|n|(ms998-ms995)/(ms997-ms995)|||2|q
~+|3.21|1|y|mo"colpro"|n|mo"colpro"*ms999|||y|1,%1%||2|q
~/ ----------------------------------------------------------------------
~/ --- Balance hb shop attractions to hb shop productions
~/ ----------------------------------------------------------------------
~+|3.21|1|y|ms997|n|mo"hsppro"|||n||2|q
~+|3.21|1|y|ms998|n|md"hspatt"|||n||2|q
~+|3.21|1|y|ms995|n|md"hspatt"|||y|%2%,%3%|||2|q
~+|3.21|1|y|ms999|n|(ms997-ms995)/(ms998-ms995)|||2|q
~+|3.21|1|y|md"hspatt"|n|md"hspatt"*ms999|||y|1,%1%||2|q
~/ ----------------------------------------------------------------------
~/ --- Balance hb other attractions to hb other productions
~/ ----------------------------------------------------------------------
~+|3.21|1|y|ms997|n|mo"hbopro"|||n||2|q
~+|3.21|1|y|ms998|n|md"hboatt"|||n||2|q
~+|3.21|1|y|ms995|n|md"hboatt"|||y|%2%,%3%|||2|q
~+|3.21|1|y|ms999|n|(ms997-ms995)/(ms998-ms995)|||2|q
~+|3.21|1|y|md"hboatt"|n|md"hboatt"*ms999|||y|1,%1%||2|q
~/ ----------------------------------------------------------------------
~/ --- Balance nhb work-other attractions to nhb work-other productions
~/ ----------------------------------------------------------------------
~+|3.21|1|y|ms997|n|mo"wkopro"|||n||2|q
~+|3.21|1|y|ms998|n|md"wkoatt"|||n||2|q
~+|3.21|1|y|ms995|n|md"wkoatt"|||y|%2%,%3%|||2|q
~+|3.21|1|y|ms999|n|(ms997-ms995)/(ms998-ms995)|||2|q
~+|3.21|1|y|md"wkoatt"|n|md"wkoatt"*ms999|||y|1,%1%||2|q
~/ ----------------------------------------------------------------------
~/ --- Set zonal nhb work-other productions equal to zonal nhb work-other attractions
~/ ----------------------------------------------------------------------
~+|3.21|1|y|mo"wkopro"|n|md"wkoatt"'|||n|2|q
~/ ----------------------------------------------------------------------
~/ --- Balance nhb other-other attractions to nhb other-other productions
~/ ----------------------------------------------------------------------
~+|3.21|1|y|ms997|n|mo"otopro"|||n||2|q
~+|3.21|1|y|ms998|n|md"otoatt"|||n||2|q
~+|3.21|1|y|ms995|n|md"otoatt"|||y|%2%,%3%|||2|q
~+|3.21|1|y|ms999|n|(ms997-ms995)/(ms998-ms995)|||2|q
~+|3.21|1|y|md"otoatt"|n|md"otoatt"*ms999|||y|1,%1%||2|q
~/ ----------------------------------------------------------------------
~/ --- Set zonal nhb other-other productions equal to zonal nhb other-other attractions
~/ ----------------------------------------------------------------------
~+|3.21|1|y|mo"otopro"|n|md"otoatt"'|||n|2|q
~/ ----------------------------------------------------------------------
~/ --- Balance hb work attractions (income 1) to hb work productions (income 1)
~/ ----------------------------------------------------------------------
~+|3.21|1|y|ms997|n|mo"hbwpr1"|||n||2|q
~+|3.21|1|y|ms998|n|md"hbwat1"|||n||2|q
~+|3.21|1|y|ms995|n|md"hbwat1"|||y|%2%,%3%|||2|q
~+|3.21|1|y|ms999|n|(ms997-ms995)/(ms998-ms995)|||2|q
~+|3.21|1|y|md"hbwat1"|n|md"hbwat1"*ms999|||y|1,%1%||2|q
~/ ----------------------------------------------------------------------
~/ --- Balance hb work attractions (income 2) to hb work productions (income 2)
~/ ----------------------------------------------------------------------
~+|3.21|1|y|ms997|n|mo"hbwpr2"|||n||2|q
~+|3.21|1|y|ms998|n|md"hbwat2"|||n||2|q
~+|3.21|1|y|ms995|n|md"hbwat2"|||y|%2%,%3%|||2|q
~+|3.21|1|y|ms999|n|(ms997-ms995)/(ms998-ms995)|||2|q
~+|3.21|1|y|md"hbwat2"|n|md"hbwat2"*ms999|||y|1,%1%||2|q
~/ ----------------------------------------------------------------------
~/ --- Balance hb work attractions (income 3) to hb work productions (income 3)
~/ ----------------------------------------------------------------------
~+|3.21|1|y|ms997|n|mo"hbwpr3"|||n||2|q
~+|3.21|1|y|ms998|n|md"hbwat3"|||n||2|q
~+|3.21|1|y|ms995|n|md"hbwat3"|||y|%2%,%3%|||2|q
~+|3.21|1|y|ms999|n|(ms997-ms995)/(ms998-ms995)|||2|q
~+|3.21|1|y|md"hbwat3"|n|md"hbwat3"*ms999|||y|1,%1%||2|q
~/ ----------------------------------------------------------------------
~/ --- Balance hb work attractions (income 4) to hb work productions (income 4)
~/ ----------------------------------------------------------------------
~+|3.21|1|y|ms997|n|mo"hbwpr4"|||n||2|q
~+|3.21|1|y|ms998|n|md"hbwat4"|||n||2|q
~+|3.21|1|y|ms995|n|md"hbwat4"|||y|%2%,%3%|||2|q
~+|3.21|1|y|ms999|n|(ms997-ms995)/(ms998-ms995)|||2|q
~+|3.21|1|y|md"hbwat4"|n|md"hbwat4"*ms999|||y|1,%1%||2|q
~/ ----------------------------------------------------------------------
~/ --- Balance hb school productions to hb school attractions by school district
~/ ----------------------------------------------------------------------
~x=20
~:sub-area loop
~/  balancing sub-zone %x%
~+|3.21|1|y|ms997|n|mo"schpro"||mo"schdst"|%x%,%x%,include|n||2|q
~+|3.21|1|y|ms998|n|md"schatt"||md"schdst"|%x%,%x%,include|n||2|q
~+|3.21|1|y|ms999|n|ms998/ms997|||2|q
~+|3.21|1|y|mo"schpro"|n|mo"schpro"*ms999||mo"schdst"|%x%,%x%,include|n|2|q
~x-1
~?x>0
~$sub-area loop
~/ ----------------------------------------------------------------------
~/ --- Exit emme
~/ ----------------------------------------------------------------------
q
