~?!i&32768
~o|295
batchin=?
reports=wto.rpt
~/
~/ ...call module 3.22: matrix balancing
~/ ...two dimensional balancing
~/ ...matrix to be balanced: mf"temp03"
~/ ...totals on origins: mo"wkopro"
~/ ...totals on destinations: md"wkoatt"
~/ ...saved balanced matrix: mf"wkodst"
~/ ...calculate nhb work/other distribution
3.22
~+|1|mf"temp03"|mo"wkopro"|md"wkoatt"|y
~+|1,%3%||1,%3%|||2|1|mf"wkodst"|n|2
q
~#
~/end: 3_calculate_distribution.mac
~/exit emme
~/
q
