~?!i&32768
~o|295
batchin=?
reports=non_motorized.rpt
~/ ----------------------------------------------------
~/ --- Initialize matrix directory
~/ ----------------------------------------------------
~+|3.12|7|y|q
~/ ----------------------------------------------------
~/ --- Initialize Matrices
~/ ----------------------------------------------------
3.12
~/ ----------------------------------------------------
~/ --- Initialize Full Matrices
~/ ----------------------------------------------------
~+|1|mf01|awlkds|am walk distance|0
~+|1|mf02|awlktm|am walk time|0
~+|1|mf03|abkeds|am bike distance|0
~+|1|mf04|abketm|am bike time|0
~+|1|mf05|izdist|intrazonal distance|0
~+|1|mf06|izbtim|intrazonal time (bike) @ 10 mph|0
~+|1|mf07|izwtim|intrazonal time (walk) @ 3 mph|0
q
~/ ----------------------------------------------------
~/ --- Import AM Scenario and Matrices
~/ ----------------------------------------------------
s=9999
1.22
~+|2|1002|~?!e|y|~?q=0|
q
~+|1.31|1
..\..\..\Assignments\AM\emmebank
~+|2|1|3|1002||n
~+|2|3|3|mf"awlktm"|mf"awlktm"|n|y
~+|2|3|3|mf"abketm"|mf"abketm"|n|y|q
s=1002
~/ ----------------------------------------------------
~/ --- Import Intrazonal Matrices
~/ ----------------------------------------------------
~+|1.31|1
..\..\iz_tt\emmebank
~+|2|3|3|mf"izdist"|mf"izdist"|n|y
~+|2|3|3|mf"izwtim"|mf"izwtim"|n|y
~+|2|3|3|mf"izbtim"|mf"izbtim"|n|y
q
~/ ----------------------------------------------------
~/ --- Calculate Non-Motorized Skims
~/ ----------------------------------------------------
3.21
~+|1|y|mf"awlkds"|n|mf"awlktm"*(3/60)|||n|2
~+|1|y|mf"abkeds"|n|mf"abketm"*(10/60)|||n|2
~+|1|y|mf"awlktm"|n|mf"awlktm"+mf"izwtim"|||n|2
~+|1|y|mf"abketm"|n|mf"abketm"+mf"izbtim"|||n|2
~+|1|y|mf"awlkds"|n|mf"awlkds"+mf"izdist"|||n|2
~+|1|y|mf"abkeds"|n|mf"abkeds"+mf"izdist"|||n|2
q
~/
~/exit emme
~/
q
