~?!i&32768
~o|295
batchin=?
reports=5_import_iz_matrices.rpt
~/
~/
~/begin: 5_import_iz_matrices.mac
~/ ...call module 1.31: import data from external database
1.31
~/ ...open intrazonal/terminal time emmebank
~+|1
..\..\iz_tt\emmebank
~/ ...import intrazonal/terminal time matrices
~+|2|3|3|mf"izdist"|mf"izdist"|n|y
~+|2|3|3|mf"izwtim"|mf"izwtim"|n|y
~+|2|3|3|mf"izbtim"|mf"izbtim"|n|y
q
~#
~/end: 5_import_iz_matrices.mac
~/exit emme
~/
q