~?!i&32768
~o|295
batchin=?
reports=14_calculate_bike_utility.rpt
~/
~/
~/begin: 14_calculate_bike_utility.mac
~/ ...call module 3.21: matrix calculations
~/ ...calculate hb work income 2 mode choice exponentiated utilities
3.21
~/ ...bike
~+|1|y|mf"wkeubk"|n
exp
(
ms"asccbk"
+
ms"biketm"*mf"abketm"
)
~+|||y|1,%1%||1,%1%||2
q
~#
~/end: 14_calculate_bike_utility.mac
~/exit emme
~/
q
