~?!i&32768
~o|295
batchin=?
reports=initialization.rpt
~/ ...initialize partitions
~/ ...input/modify zone groups (using batch entry)
3.01
~+|4|all|y
~+|1|..\..\parameters\ensembles\districts19_ga.ens|2
~+|1|..\..\parameters\ensembles\seattlecbd_gb.ens|2
~+|1|..\..\parameters\ensembles\counties_gc.ens|2
~+|1|..\..\parameters\ensembles\districts6_gk.ens|2
~+|1|..\..\parameters\ensembles\kitsap_gl.ens|2
q
~#
~/end: 3_load_ensembles.mac
~/exit emme
~/
q
