~?!i&32768
~o|295
batchin=?
reports=initialization.rpt
~/ ---------------------------------------------------------------------
~/ --- Truck Inputs
~/ ---------------------------------------------------------------------
~+|3.11|..\..\input\externals\trucks\medium_trucks_ee.in|2|
~+|3.11|..\..\input\externals\trucks\medium_trucks_ei.in|2|
~+|3.11|..\..\input\externals\trucks\medium_trucks_ie.in|2|
~+|3.11|..\..\input\externals\trucks\heavy_trucks_ee.in|2|
~+|3.11|..\..\input\externals\trucks\heavy_trucks_ei.in|2|
~+|3.11|..\..\input\externals\trucks\heavy_trucks_ie.in|2|
~/ ---------------------------------------------------------------------
~/ --- Exit Emme
~/ ---------------------------------------------------------------------
q
