~?!i&32768
~o|295
batchin=?
reports=initialization.rpt
~/
~/ ...input heavy truck external-external trips
3.11
~+|..\..\input\Externals\Trucks\heavy_trucks_reeb_ee.in|2|
~/ ...input heavy truck external-internal trips
3.11
~+|..\..\input\Externals\Trucks\heavy_trucks_reeb_ei.in|2|
~/ ...input heavy truck internal-external trips
3.11
~+|..\..\input\Externals\Trucks\heavy_trucks_reeb_ie.in|2|
~#
~/end: 8_input_data.mac
~/exit emme
~/
q
