~?!i&32768
~o|295
batchin=?
reports=hbw3.rpt
~/
~/ ...call module 3.21: matrix calculations
~/ ...calculate hb work income 3 mode choice exponentiated utilities
3.21
~/ ...transit drive-access
~+|1|y|mf"eutd"|n
exp
(
ms"ascctd"
+
ms"trdivt"*(mf"pnrtm"+mf"ivtda")
+
ms"trdovt"*(mf"wlkda"+mf"iwtda"+mf"xfrda")
+
ms"trdcos"*(mf"dapct"+mf"farda")
)
~+|||y|1,%1%||1,%1%||2
q
~#
~/end: 8_calculate_transit_drive_access_utility.mac
~/exit emme
~/
q
