~?!i&32768
~o|295
batchin=?
reports=2_initialize_am_full_matrices.rpt
~/
~/
~/begin: 2_initialize_am_full_matrices.mac
~/ ...set active scenario to 1002
s=1002
~/ ...call module 3.12: input/modify matrices interactively
~/ ...initialize full matrices
3.12
~+|1|mf01|awalk|am walk person trip table|0
~+|1|mf02|awlktm|am walk time|0
~+|1|mf03|abike|am bike person trip table|0
~+|1|mf04|abketm|am bike time|0
q
~#
~/end: 2_initialize_am_full_matrices.mac
~/exit emme
~/
q
