~?!i&32768
~o|295
batchin=?
reports=4_initialize_am_vdfs.rpt
~/
~/
~/begin: 4_initialize_am_vdfs.mac
~/ ...set active scenario to 1002
s=1002
~/ ...call module 4.12: input/modify functions interactively
~/ ...initialize function table
4.12
~+|1|y
q
~/ ...call module 4.11: input functions using batch entry
~/ ...input am vdfs
4.11
..\..\..\model\vdfs\am_vdfs.in
2
~#
~/end: 4_initialize_am_vdfs.mac
~/exit emme
~/
q
