cd vehicleavailability
call batchfiles\vehicle_availability.bat
cd ..
cd marketsegmentation
call batchfiles\market_segmentation_tg.bat
cd ..
cd distribution
call batchfiles\trip_distribution_tg.bat
cd ..
cd trucks
call batchfiles\truck_distribution.bat
cd ..
cd modechoice
call batchfiles\mode_choice.bat
cd ..
cd timeofday
call batchfiles\tod\time_of_day_model.bat
call batchfiles\check\tod_completion_check.bat
cd ..
cd triptables\parkandride
call batchfiles\pnr_trip_tables.bat
call batchfiles\pnr_trip_tables_completion_check.bat
cd ..\..
cd triptables\autos
call batchfiles\auto_trip_tables.bat
call batchfiles\auto_trip_tables_completion_check.bat
cd ..\..
cd triptables\transit
call batchfiles\transit_walk_access_trip_tables.bat
cd ..\..
cd triptables\nonmotorized
call batchfiles\all_nonmotorized_trip_tables.bat
cd ..\..
cd triptables\trucks
call batchfiles\truck_trip_tables.bat
cd ..\..
cd assignments\auto
call batchfiles\setup\congested\congested_assignment_setup.bat
call batchfiles\congested\parallel_congested_assign.bat
call batchfiles\check\assignment_completion_check.bat
call batchfiles\summaries\auto_network_summary.bat
cd ..\..
cd assignments\transit
call batchfiles\congested\congested_transit_assign.bat
cd ..\..
cd skims\auto
call batchfiles\basic\auto_skims.bat
call batchfiles\check\auto_skim_completion_check.bat
cd ..\..
cd skims\bidirectional
call batchfiles\bidirectional_skims.bat
cd ..\..
cd skims\transit
call batchfiles\basic\basic_transit_skims.bat
cd ..\..
cd skims\pnr
call batchfiles\pnr_skims.bat
call batchfiles\pnr_skim_completion_check.bat
cd ..\..