~?!i&32768
~o|295
~/ ------------------------------------------------------------------------
~/ Summary Data - Vehicles, VMT, VHT, Delay and Avg. Speed by facility type
~/ ------------------------------------------------------------------------
,1002
reports=?
batchout=?
2.41
~/ --- Total Vehicles ---
~+|1|n|volau||ul3=1,2||2|2|..\validation\modelstats\mstat.txt
~+|1|n|volau||ul3=3,4|ul3=6||2|2
~+|1|n|volau||ul3=5||2|2
~+|1|n|volau||ul3=1,6||2|2
~/ --- VMT (vehicle-miles) ---
~+|1|n|volau*len||ul3=1,2||2|2
~+|1|n|volau*len||ul3=3,4|ul3=6||2|2
~+|1|n|volau*len||ul3=5||2|2
~+|1|n|volau*len||ul3=1,6||2|2
~/ --- VHT (vehicle-hours) ---
~+|1|n|volau*timau||ul3=1,2||2|2
~+|1|n|volau*timau||ul3=3,4|ul3=6||2|2
~+|1|n|volau*timau||ul3=5||2|2
~+|1|n|volau*timau||ul3=1,6||2|2
~/ --- Delay (vehicle-hours) ---
~+|1|n|volau*(timau-(len*60/ul2))/60||ul3=1,2||2|2
~+|1|n|volau*(timau-(len*60/ul2))/60||ul3=3,4|ul3=6||2|2
~+|1|n|volau*(timau-(len*60/ul2))/60||ul3=1,6||2|2
~/ --- Numerator for Avg. Speed ---
~+|1|n|volau*len*60/timau||ul3=1,2||2|2
~+|1|n|volau*len*60/timau||ul3=3,4|ul3=6||2|2
~+|1|n|volau*len*60/timau||ul3=5||2|2
~+|1|n|volau*len*60/timau||ul3=1,6||2|2
~/ --- PMT in Private Vehicles ---
~+|1|n|(@sov+@hbw1+@hbw2+@hbw3+@hbw4)*len||ul3=1,6||2|2
~+|1|n|(@hov2*2*len)+(@hov3*3.5*len)+(@vpool*8*len)||ul3=1,6||2|2
~+|6
q